# Copyright 2016, 2017 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

# When copying this to a new library, be sure to update the name of the library
# in two places (once each at the top of install: and test_script:)

version: 1.0.{build}-{branch}

shallow_clone: true

#branches:
#  only:
#    - develop
#    - master

image:
  - Visual Studio 2017

platform:
  - msvc-14.1
  - msvc-14.0
  - msvc-12.0
  - msvc-11.0
  - msvc-10.0

configuration:
  - test/x3
  - test/qi
  - test/karma
  - test/lex
  - test/support

environment:
  global:
    PROJECT: libs/spirit
    B2_ADDRESS_MODEL: address-model=64
    B2_LINK: link=shared
    B2_THREADING: threading=multi
    B2_VARIANT: variant=release

matrix:
  fast_finish: true
  exclude:
    - configuration: test/x3
      platform: msvc-14.0
    - configuration: test/x3
      platform: msvc-12.0
    - configuration: test/x3
      platform: msvc-11.0
    - configuration: test/x3
      platform: msvc-10.0

install:
  - set SELF=spirit
  - cd ..
  - git clone -j10 --branch=develop --depth=1 --quiet --recurse-submodules=":(exclude)$PROJECT" --shallow-submodules https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - xcopy /s /e /q /Y %APPVEYOR_BUILD_FOLDER% libs\%SELF%
  - cmd /c bootstrap
  - b2 headers

build: off

test_script:
  - set SELF=spirit
  - PATH=%ADDPATH%%PATH%
  - b2 libs/%SELF%/%CONFIGURATION% toolset=%PLATFORM% %CXXFLAGS% %B2_ADDRESS_MODEL% %B2_LINK% %B2_THREADING% %B2_VARIANT% -j3
